apiVersion: network.oci.upbound.io/v1alpha1
kind: LoadBalancerNetworkLoadBalancer
metadata:
  annotations:
    meta.upbound.io/example-id: network/v1alpha1/loadbalancernetworkloadbalancer
  labels:
    testing.upbound.io/example-name: test_network_load_balancer
  name: test-network-load-balancer
spec:
  forProvider:
    compartmentIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    definedTags:
      Operations.CostCenter: "42"
    displayName: ${var.network_load_balancer_display_name}
    freeformTags:
      Department: Finance
    isPreserveSourceDestination: ${var.network_load_balancer_is_preserve_source_destination}
    isPrivate: ${var.network_load_balancer_is_private}
    networkSecurityGroupIds: ${var.network_load_balancer_network_security_group_ids}
    nlbIpVersion: ${var.network_load_balancer_nlb_ip_version}
    reservedIps:
    - id: ${var.network_load_balancer_reserved_ips_id}
    subnetIdSelector:
      matchLabels:
        testing.upbound.io/example-name: test_subnet

---

