apiVersion: file.oci.upbound.io/v1alpha1
kind: StorageMountTarget
metadata:
  annotations:
    meta.upbound.io/example-id: file/v1alpha1/storagemounttarget
  labels:
    testing.upbound.io/example-name: test_mount_target
  name: test-mount-target
spec:
  forProvider:
    availabilityDomain: ${var.mount_target_availability_domain}
    compartmentIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    definedTags:
      Operations.CostCenter: "42"
    displayName: ${var.mount_target_display_name}
    freeformTags:
      Department: Finance
    hostnameLabel: ${var.mount_target_hostname_label}
    ipAddress: ${var.mount_target_ip_address}
    nsgIds: ${var.mount_target_nsg_ids}
    subnetIdSelector:
      matchLabels:
        testing.upbound.io/example-name: test_subnet
