apiVersion: objectstorage.oci.jet.crossplane.io/v1alpha1
kind: ObjectLifecyclePolicy
metadata:
  name: object-lifecycle-policy-via-crossplane
spec:
  forProvider:
    bucket: test-for-crossplane
    namespace: dex-us-phoenix-1-manual
    rules:
      - action: ARCHIVE
        target: objects
        isEnabled: true
        name: policy-via-crossplane
        timeAmount: "30"
        timeUnit: DAYS
