apiVersion: load.oci.upbound.io/v1alpha1
kind: BalancerListener
metadata:
  name: lblistener
spec:
  forProvider:
    loadBalancerIdRef:
      name: loadbalancer-via-crossplane
    defaultBackendSetName: "lbbackendset-via-crossplane"
    name: "lblistener"
    port: 10
    protocol: "HTTP"