apiVersion: load.oci.upbound.io/v1alpha1
kind: BalancerLoadBalancer
metadata:
  name: loadbalancer-via-crossplane
spec:
  forProvider:
    compartmentIdRef:
      name : compartment-via-crossplane5
    displayName: "alwaysFreeLoadBalancer"
    shape: "flexible"
    subnetIdsRefs:
      - name: subnet-via-crossplane5
    shapeDetails:
      - maximumBandwidthInMbps: 10
        minimumBandwidthInMbps: 10