apiVersion: load.oci.upbound.io/v1alpha1
kind: BalancerBackend
metadata:
  name: lbbackend-via-crossplane
spec:
  forProvider:
    loadBalancerIdRef:
      name: loadbalancer-via-crossplane
    backendsetName: "lbbackendset-via-crossplane"
    ipAddress: "10.0.0.3"
    port: 10