apiVersion: core.oci.upbound.io/v1alpha1
kind: PrivateIP
metadata:
  annotations:
    meta.upbound.io/example-id: core/v1alpha1/privateip
  labels:
    testing.upbound.io/example-name: test_private_ip
  name: test-private-ip
spec:
  forProvider:
    definedTags:
      Operations.CostCenter: "42"
    displayName: ${var.private_ip_display_name}
    freeformTags:
      Department: Finance
    hostnameLabel: ${var.private_ip_hostname_label}
    ipAddress: ${var.private_ip_ip_address}
    vlanIdSelector:
      matchLabels:
        testing.upbound.io/example-name: test_vlan
    vnicIdSelector:
      matchLabels:
        testing.upbound.io/example-name: test_vnic_attachment
