apiVersion: logging.oci.upbound.io/v1alpha1
kind: UnifiedAgentConfiguration
metadata:
  name: unifiedagentconfiguration-via-crossplane
spec:
  forProvider:
    compartmentIdRef:
      name : compartment-via-crossplane5
    isEnabled: true
    serviceConfiguration:
        - configurationType: "LOGGING"
          destination:
            - logObjectId: "ocid1.log.oc1.phx.ssss"
          sources:
            - sourceType: "WINDOWS_EVENT_LOG"
    groupAssociation:
      - groupList:
          ["ocid1.loggroup.oc1.phx.ssss"]
