apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: okecluster
spec:
  writeConnectionSecretsToNamespace: crossplane-system
  compositeTypeRef:
    apiVersion: oci.jet.crossplane.io/v1alpha1
    kind: CompositeContainerEngine
  resources:

  - name: compartment 
    base:
      apiVersion: identity.oci.jet.crossplane.io/v1alpha1
      kind: Compartment
      spec:
        forProvider:
          compartmentId: "ocid1.compartment.oc1..xxx"
          description: "Compartment via crossplane to test OKE"
          name: "compartmentokecluster101"
          enableDelete : True

  - name: vcn
    base:
      apiVersion: core.oci.jet.crossplane.io/v1alpha1
      kind: Vcn
      metadata:
        name: vcn
      spec:
        forProvider:
          compartmentIdSelector:
            matchControllerRef: true
          region: "ap-hyderabad-1"
          cidrBlocks: [10.0.0.0/16]
    patches:
      - type: ToCompositeFieldPath
        fromFieldPath: status.atProvider.id
        toFieldPath:  status.vcnId
  
  # - name: privatesecuritylist
  #   base:
  #     apiVersion: core.oci.jet.crossplane.io/v1alpha1
  #     kind: SecurityList
  #     spec:
  #       forProvider:
  #         compartmentIdSelector:
  #           matchControllerRef: true
  #         vcnIdSelector:
  #           matchControllerRef: true
  #         displayName:  "security-list-for-private-subnet"
  #         egressSecurityRules :
  #           - stateless : false
  #             destination : "0.0.0.0/0"
  #             destination_type: "CIDR_BLOCK"
  #             protocol: "all" 
  #         ingress_security_rules :
  #           - stateless: false
  #             source: "10.0.0.0/16"
  #             sourceType: "CIDR_BLOCK"
  #             protocol: "6"
  #             tcpOptions:
  #               min: 22
  #               max: 22
  #           - stateless: false
  #             source: "0.0.0.0/0"
  #             sourceType: "CIDR_BLOCK"
  #             protocol: "1"
  #             icmpOptions:
  #               min: 3
  #               max: 4
  #           - stateless: false
  #             source: "10.0.0.0/16"
  #             sourceType: "CIDR_BLOCK"
  #             protocol: "1"
  #             icmpOptions:
  #               min: 3

  # - name: publicsecuritylist
  #   base:
  #     apiVersion: core.oci.jet.crossplane.io/v1alpha1
  #     kind: SecurityList
  #     spec:
  #       forProvider:
  #         compartmentIdSelector:
  #           matchControllerRef: true
  #         vcnIdSelector:
  #           matchControllerRef: true
  #         displayName:  "security-list-for-public-subnet"
  #         egressSecurityRules :
  #           - stateless : false
  #             destination : "0.0.0.0/0"
  #             destination_type: "CIDR_BLOCK"
  #             protocol: "all" 
  #         ingress_security_rules :
  #           - stateless: false
  #             source: "0.0.0.0/0"
  #             sourceType: "CIDR_BLOCK"
  #             protocol: "6"
  #             tcpOptions:
  #               min: 22
  #               max: 22
  #           - stateless: false
  #             source: "0.0.0.0/0"
  #             sourceType: "CIDR_BLOCK"
  #             protocol: "1"
  #             icmpOptions:
  #               min: 3
  #               max: 4
  #           - stateless: false
  #             source: "10.0.0.0/16"
  #             sourceType: "CIDR_BLOCK"
  #             protocol: "1"
  #             icmpOptions:
  #               min: 3

  - name: privatesubnet
    base:
      apiVersion: core.oci.jet.crossplane.io/v1alpha1
      kind: Subnet
      metadata:
        labels:
          access: privatesubnet
      spec:
        forProvider:
          compartmentIdSelector:
            matchControllerRef: true
          vcnIdSelector:
            matchControllerRef: true
          cidrBlock: "10.0.1.0/24"
          displayName : "private-subnet"
    patches:
      - type: ToCompositeFieldPath
        fromFieldPath: status.atProvider.id
        toFieldPath:  status.privateSubnetId


# # TODO propogate natgwy route id
#   - name: natgwy
#     base:
#       apiVersion: core.oci.jet.crossplane.io/v1alpha1
#       kind: NATGateway
#       spec:
#         forProvider:
#           compartmentIdSelector:
#             matchControllerRef: true
#           vcnIdSelector:
#             matchControllerRef: true
#     # patches:
#     # - type: ToCompositeFieldPath
#     #   fromFieldPath: status.atProvider.id
#     #   toFieldPath:  status.privateSubnetId


# #TODO propogate internetgwy route id
#   - name: internetgwy
#     base:
#       apiVersion: core.oci.jet.crossplane.io/v1alpha1
#       kind: InternetGateway
#       spec:
#         forProvider:
#           compartmentIdSelector:
#             matchControllerRef: true
#           vcnIdSelector:
#             matchControllerRef: true
#     # patches:
#     # - type: ToCompositeFieldPath
#     #   fromFieldPath: status.atProvider.id
#     #   toFieldPath:  status.privateSubnetId


  - name: okecluster
    base:
      apiVersion: containerengine.oci.jet.crossplane.io/v1alpha1
      kind: Cluster
      spec:
        forProvider:
          compartmentIdSelector:
            matchControllerRef: true
          kubernetesVersion : "v1.22.5"
          name: "sks-oke-cluster"
          vcnIdSelector:
            matchControllerRef: true
          # options:
          #   - add_ons:
          #       isKubernetesDashboardEnabled : false
          #       isTillerEnabled : false
          #     kubernetes_network_config:
          #       podsCidr: "10.244.0.0/16"
          #       servicesCidr : "10.96.0.0/16"
    patches:
      - type: FromCompositeFieldPath
        fromFieldPath: spec.parameters.name
        toFieldPath: spec.forProvider.name

  - name: okenodepool
    base:
      apiVersion: containerengine.oci.jet.crossplane.io/v1alpha1
      kind: NodePool
      spec:
        forProvider:
          compartmentIdSelector:
            matchControllerRef: true
          kubernetesVersion : "v1.22.5"
          name: "default"
          clusterIdSelector:
            matchControllerRef: true
          nodeConfigDetails:
            - placementConfigs:
              - availabilityDomain : "xxx:AP-HYDERABAD-1-AD-1"
                subnetId : ""
              size : 2
          nodeShape: "VM.Standard2.1"
          nodeSourceDetails:
            - imageId : "ocid1.image.oc1.ap-hyderabad-1.xxx"
              sourceType : "image"
    patches:
      - type: FromCompositeFieldPath
        fromFieldPath: status.privateSubnetId
        toFieldPath: spec.forProvider.nodeConfigDetails[0].placementConfigs[0].subnetId
      - type: FromCompositeFieldPath
        fromFieldPath: spec.parameters.name
        toFieldPath: spec.forProvider.name
      - type: FromCompositeFieldPath
        fromFieldPath: spec.parameters.numberOfNodes
        toFieldPath: spec.forProvider.nodeConfigDetails[0].size
      
        # policy:
        #   fromFieldPath: Required

# #   # - name: routetable
# #   #   base:
# #   #     apiVersion: core.oci.jet.crossplane.io/v1alpha1
# #   #     kind: RouteTable
# #   #     spec:
# #   #       forProvider:
# #   #         compartmentId: 'ocid1.compartment.oc1..xxx'
# #   #         vcnId: 'ocid1.vcn.oc1.ap-hyderabad-1.xxx'
# #   #         routeRules:
# #   #           - description: "Route Table route"
# #   #             destination: "10.0.0.0/28"
# #   #             sourceType: "CIDR_BLOCK"
# #   #             networkEntityId: ""

# #   #   patches:
# #   #   - type: FromCompositeFieldPath
# #   #     fromFieldPath: status.natGwId
# #   #     toFieldPath: spec.forProvider.routeRules[0].networkEntityId
# #   #     policy:
# #   #       fromFieldPath: Required


