apiVersion: load.oci.upbound.io/v1alpha1
kind: BalancerHostname
metadata:
  annotations:
    meta.upbound.io/example-id: load/v1alpha1/balancerhostname
  labels:
    testing.upbound.io/example-name: test_hostname
  name: test-hostname
spec:
  forProvider:
    hostname: ${var.hostname_hostname}
    loadBalancerIdSelector:
      matchLabels:
        testing.upbound.io/example-name: test_load_balancer
    name: ${var.hostname_name}

---

