apiVersion: network.oci.upbound.io/v1alpha1
kind: FirewallNetworkFirewallPolicy
metadata:
  annotations:
    meta.upbound.io/example-id: network/v1alpha1/firewallnetworkfirewallpolicy
  labels:
    testing.upbound.io/example-name: test_network_firewall_policy
  name: test-network-firewall-policy
spec:
  forProvider:
    application_lists:
    - application_list_name: ${var.network_firewall_policy_application_lists_key}
      application_values:
      - icmp_code: ${var.network_firewall_policy_application_lists_icmp_code}
        icmp_type: ${var.network_firewall_policy_application_lists_icmp_type}
        maximum_port: ${var.network_firewall_policy_application_lists_maximum_port}
        minimum_port: ${var.network_firewall_policy_application_lists_minimum_port}
        type: ${var.network_firewall_policy_application_lists_type}
    compartmentIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    decryption_profiles:
    - are_certificate_extensions_restricted: ${var.network_firewall_policy_decryption_profiles_are_certificate_extensions_restricted}
      is_auto_include_alt_name: ${var.network_firewall_policy_decryption_profiles_is_auto_include_alt_name}
      is_expired_certificate_blocked: ${var.network_firewall_policy_decryption_profiles_is_expired_certificate_blocked}
      is_out_of_capacity_blocked: ${var.network_firewall_policy_decryption_profiles_is_out_of_capacity_blocked}
      is_revocation_status_timeout_blocked: ${var.network_firewall_policy_decryption_profiles_is_revocation_status_timeout_blocked}
      is_unknown_revocation_status_blocked: ${var.network_firewall_policy_decryption_profiles_is_unknown_revocation_status_blocked}
      is_unsupported_cipher_blocked: ${var.network_firewall_policy_decryption_profiles_is_unsupported_cipher_blocked}
      is_unsupported_version_blocked: ${var.network_firewall_policy_decryption_profiles_is_unsupported_version_blocked}
      is_untrusted_issuer_blocked: ${var.network_firewall_policy_decryption_profiles_is_untrusted_issuer_blocked}
      type: ${var.network_firewall_policy_decryption_profiles_type}
    decryption_rules:
    - action: ${var.network_firewall_policy_decryption_rules_action}
      condition:
      - destinations: ${var.network_firewall_policy_decryption_rules_condition_destinations}
        sources: ${var.network_firewall_policy_decryption_rules_condition_sources}
      decryption_profile: ${var.network_firewall_policy_decryption_rules_decryption_profile}
      name: ${var.network_firewall_policy_decryption_rules_name}
      secret: ${var.network_firewall_policy_decryption_rules_secret}
    definedTags:
      foo-namespace.bar-key: value
    displayName: ${var.network_firewall_policy_display_name}
    freeformTags:
      bar-key: value
    ip_address_lists:
    - ip_address_list_name: ${var.network_firewall_policy_ip_address_lists_name}
      ip_address_list_value: ${var.network_firewall_policy_ip_address_lists_value}
    mapped_secrets:
    - source: ${var.network_firewall_policy_mapped_secrets_source}
      type: ${var.network_firewall_policy_mapped_secrets_type}
      vault_secret_id: ${oci_vault_secret.test_secret.id}
      version_number: ${var.network_firewall_policy_mapped_secrets_version_number}
    security_rules:
    - action: ${var.network_firewall_policy_security_rules_action}
      condition:
      - applications: ${var.network_firewall_policy_security_rules_condition_applications}
        destinations: ${var.network_firewall_policy_security_rules_condition_destinations}
        sources: ${var.network_firewall_policy_security_rules_condition_sources}
        urls: ${var.network_firewall_policy_security_rules_condition_urls}
      inspection: ${var.network_firewall_policy_security_rules_inspection}
      name: ${var.network_firewall_policy_security_rules_name}
    url_lists:
    - url_list_name: ${var.network_firewall_policy_url_lists_key}
      url_list_values:
      - pattern: ${var.network_firewall_policy_url_lists_pattern}
        type: ${var.network_firewall_policy_url_lists_type}
