apiVersion: network.oci.upbound.io/v1alpha1
kind: LoadBalancerListener
metadata:
  annotations:
    meta.upbound.io/example-id: network/v1alpha1/loadbalancerlistener
  labels:
    testing.upbound.io/example-name: test_listener
  name: test-listener
spec:
  forProvider:
    defaultBackendSetName: ${var.backend_set_name}
    ipVersion: ${var.listener_ip_version}
    name: ${var.listener_name}
    networkLoadBalancerIdSelector:
      matchLabels:
        testing.upbound.io/example-name: test_network_load_balancer
    port: ${var.listener_port}
    protocol: ${var.listener_protocol}
