apiVersion: kms.oci.upbound.io/v1alpha1
kind: Vault
metadata:
  annotations:
    meta.upbound.io/example-id: kms/v1alpha1/vault
  labels:
    testing.upbound.io/example-name: test_vault
  name: test-vault
spec:
  forProvider:
    compartmentIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    definedTags:
      Operations.CostCenter: "42"
    displayName: ${var.vault_display_name}
    freeformTags:
      Department: Finance
    vaultType: ${var.vault_vault_type}
