apiVersion: core.oci.upbound.io/v1alpha1
kind: VolumeGroup
metadata:
  name: volumegroup1
spec:
  forProvider:
    compartmentIdRef:
      name : compartment-via-crossplane5
    availabilityDomain: "AnvB:PHX-AD-1"
    sourceDetails:
      - type : "volumeIds"
        volumeIdsRefs :
          - name: volume1
        