apiVersion: network.oci.upbound.io/v1alpha1
kind: LoadBalancerNetworkLoadBalancersBackendSetsUnified
metadata:
  name: nwlbbackendunified-via-crossplane
spec:
  forProvider:
    networkLoadBalancerIdRef: 
      name: nwlb-via-crossplane
    name: "nwlbbackendunified-via-crossplane"
    healthChecker:
      - protocol: "TCP"
    policy: "FIVE_TUPLE"