apiVersion: certificatesmanagement.oci.upbound.io/v1alpha1
kind: CertificateAuthority
metadata:
  name: certificate-authority-via-crossplane1
spec:
  forProvider:
    compartmentIdRef: 
      name : compartment-via-crossplane1
    certificateAuthorityConfig:
      - configType: ROOT_CA_GENERATED_INTERNALLY
        signingAlgorithm: "SHA256_WITH_RSA"
        subject: 
          - commonName: www.example.com
    kmsKeyId: ocid1.key.oc1.phx.bzrujfjhaad36.xxxxx
    name: certificate-authority-via-crossplane1