apiVersion: core.oci.upbound.io/v1alpha1
kind: Vlan
metadata:
  name: vlan
spec:
  forProvider:
    compartmentIdRef:
      name : compartment-via-crossplane5
    vcnIdRef:
      name: vcn-via-crossplane5
    cidrBlock: "10.20.20.8/30"