apiVersion: core.oci.upbound.io/v1alpha1
kind: InstanceConfiguration
metadata:
  name: testinstanceconf
spec:
  forProvider:
    compartmentIdRef:
      name : compartment-via-crossplane5
    instanceDetails:
      - instanceType: "compute"
        secondaryVnics:
          - displayName: "backend-servers"
            nicIndex: 0