apiVersion: core.oci.upbound.io/v1alpha1
kind: Ipsec
metadata:
  name: testipsec
spec:
  forProvider:
    compartmentIdRef:
      name : compartment-via-crossplane5
    cpeIdRef:
      name: testcpe
    drgIdRef:
      name: testdrg
    staticRoutes: ["10.0.0.0/16"]