apiVersion: v1
kind: Secret
metadata:
  name: secret-for-tsig
  namespace: crossplane-system
data:
  # Crossplane will auto decode this value, it needs to be base64 encoded for twice in order to meet the requirement of base64 string as the secret. 
  # This is the result of base64 encode for twice, the original string is 12345
  tsigSecret: BASE64VAL=