apiVersion: dns.oci.upbound.io/v1alpha1
kind: SteeringPolicy
metadata:
  name: steering-policy-via-crossplane
spec:
  forProvider:
    compartmentIdRef: 
      name : compartment-via-crossplane1
    displayName: steering-policy-via-crossplane
    template: FAILOVER
    healthCheckMonitorIdRef:
      name: http-monitor-via-crossplane
    rules:
      - ruleType: HEALTH
      - ruleType: LIMIT
        defaultCount: 1