apiVersion: dns.oci.upbound.io/v1alpha1
kind: TsigKey
metadata:
  name: tsig-key-via-crossplane
spec:
  forProvider:
    compartmentIdRef: 
      name : compartment-via-crossplane1
    name: tsig-key-via-crossplane
    algorithm: hmac-sha256
    secretSecretRef: 
      name: secret-for-tsig
      namespace: crossplane-system
      key: tsigSecret