apiVersion: servicemesh.oci.jet.crossplane.io/v1alpha1
kind: IngressGateway
metadata:
  name: ingress-gateway-via-crossplane
spec:
  forProvider:
    compartmentIdRef: 
      name : compartment-via-crossplane1
    hosts:
      - name: test-crossplane
        hostnames: 
          - test.com
        listeners:
          - port: 2054
            protocol: HTTP
    meshIdRef:
      name: mesh-via-crossplane
    name: ingress-gateway-via-crossplane
